### ISSUE TITLE
Error while installing the script with GreaseMonkey in FireFox: Ignoring @match pattern http*://scoresaber.com/* because: @match: Invalid protocol (http*:) specified.

### ISSUE THREAD

**Issue by CypherNL** [Splamy/ScoreSaberEnhanced#10]
**FireFox version:** 73.0.1
**OS:** Windows 10 1909 Education

When installing the script with GreaseMonkey on FireFox i get the following error:
`Ignoring @match pattern http*://scoresaber.com/* because: Error: @match: Invalid protocol (http*:) specified.`

This is with both installing from link or by copy-pasting it to GreaseMonkey.

**Comment by Splamy** [comment]
I know we had Greasemonkey in our readme as an option but I never tested it. Damn Greasemonkey feels old, buggy and weird...
Anyway i fixed the script to work with it now, but I still suggest to use tampermonkey, since it's the same ext I use.
Also some js errors in Greasemonkey just silently fail, so you might not even notice if a new feature is broken or just doesn't exist.
